path and sudo fixes

diff --git a/zsh/zshrc__aliases b/zsh/zshrc__aliases
--- a/zsh/zshrc__aliases
+++ b/zsh/zshrc__aliases
@@ -15,140 +15,140 @@ done
 #
 # Arguments: none
 #################################################
-is_yarn_project() {
-  if [[ -e yarn.lock ]]; then
-    return 0
-  else
-    return 1
-  fi
-}
+# is_yarn_project() {
+#   if [[ -e yarn.lock ]]; then
+#     return 0
+#   else
+#     return 1
+#   fi
+# }
 
-fm() {
-  echo "💅 Formatting files with Prettier..."
-  # This `is_yarn_project` isn't working well inside in concurrently, just ignoring and using yarn by default for now
-  # if is_yarn_project; then
-  yarn prettier --write --loglevel=error .
-  # else
-  # npx prettier --write --loglevel=error .
-  # fi
-  echo "✅ Done formatting"
-}
-# "format commit": format the files, and commit the result
-fmc() {
-  fm
+# fm() {
+#   echo "💅 Formatting files with Prettier..."
+#   # This `is_yarn_project` isn't working well inside in concurrently, just ignoring and using yarn by default for now
+#   # if is_yarn_project; then
+#   yarn prettier --write --loglevel=error .
+#   # else
+#   # npx prettier --write --loglevel=error .
+#   # fi
+#   echo "✅ Done formatting"
+# }
+# # "format commit": format the files, and commit the result
+# fmc() {
+#   fm
 
-  if git_has_changes; then
-    gcim 'cleanup'
-  fi
-}
-lint() {
-  echo "🔎 Linting files with ESLint..."
-  yarn eslint --max-warnings=0 --fix .
-  echo "✅ Done linting"
-}
-tc() {
-  echo "🧐 Type-checking files with TypeScript..."
-  yarn tsc $@ --noEmit
-  echo "✅ Done type-checking"
-}
-jest() {
-  echo "🧪 Testing files changed on branch..."
-  # Maaaaaan, Jest don't know SHIT about how many workers to use
-  # https://dev.to/vantanev/make-your-jest-tests-up-to-20-faster-by-changing-a-single-setting-i36
-  yarn jest --changedSince=$(git_dev_branch) --coverage=false --maxWorkers=50% $@
-  echo "✅ Done testing"
-}
-jestw() {
-  echo "🧪👀 Testing files on watch..."
-  yarn jest --watch --coverage=false --maxWorkers=25% $@
-  echo "✅ Done testing"
-}
-jestbw() {
-  echo "🧪👀 Testing files changed on branch on watch..."
-  yarn jest --changedSince=$(git_dev_branch) --watch --coverage=false --maxWorkers=25% $@
-  echo "✅ Done testing"
-}
-jesta() {
-  echo "🧪 Testing all files..."
-  yarn jest --coverage=false --maxWorkers=50% $@
-  echo "✅ Done testing"
-}
-vj() {
-  if is_yarn_project; then
-    yarn
-  else
-    npm i
-  fi
-  jest
-}
-# "validate static"
-vs() { (
-  # Exit and fail the function if any command in it fails. In a function, you have to add the parens to create a "subshell" in order for this to work. Without them, zsh itself crashes
-  # https://stackoverflow.com/questions/40429865/how-to-exit-bash-function-if-error
-  set -e
+#   if git_has_changes; then
+#     gcim 'cleanup'
+#   fi
+# }
+# lint() {
+#   echo "🔎 Linting files with ESLint..."
+#   yarn eslint --max-warnings=0 --fix .
+#   echo "✅ Done linting"
+# }
+# tc() {
+#   echo "🧐 Type-checking files with TypeScript..."
+#   yarn tsc $@ --noEmit
+#   echo "✅ Done type-checking"
+# }
+# jest() {
+#   echo "🧪 Testing files changed on branch..."
+#   # Maaaaaan, Jest don't know SHIT about how many workers to use
+#   # https://dev.to/vantanev/make-your-jest-tests-up-to-20-faster-by-changing-a-single-setting-i36
+#   yarn jest --changedSince=$(git_dev_branch) --coverage=false --maxWorkers=50% $@
+#   echo "✅ Done testing"
+# }
+# jestw() {
+#   echo "🧪👀 Testing files on watch..."
+#   yarn jest --watch --coverage=false --maxWorkers=25% $@
+#   echo "✅ Done testing"
+# }
+# jestbw() {
+#   echo "🧪👀 Testing files changed on branch on watch..."
+#   yarn jest --changedSince=$(git_dev_branch) --watch --coverage=false --maxWorkers=25% $@
+#   echo "✅ Done testing"
+# }
+# jesta() {
+#   echo "🧪 Testing all files..."
+#   yarn jest --coverage=false --maxWorkers=50% $@
+#   echo "✅ Done testing"
+# }
+# vj() {
+#   if is_yarn_project; then
+#     yarn
+#   else
+#     npm i
+#   fi
+#   jest
+# }
+# # "validate static"
+# vs() { (
+#   # Exit and fail the function if any command in it fails. In a function, you have to add the parens to create a "subshell" in order for this to work. Without them, zsh itself crashes
+#   # https://stackoverflow.com/questions/40429865/how-to-exit-bash-function-if-error
+#   set -e
 
-  local index_dirty=0
-  if git_has_changes; then
-    echo "Uncommitted changes found; will not commit cleanup changes."
-    index_dirty=1
-  fi
+#   local index_dirty=0
+#   if git_has_changes; then
+#     echo "Uncommitted changes found; will not commit cleanup changes."
+#     index_dirty=1
+#   fi
 
-  if is_yarn_project; then
-    yarn
-  else
-    npm i
-  fi
+#   if is_yarn_project; then
+#     yarn
+#   else
+#     npm i
+#   fi
 
-  # NOTE: Since concurrently doesn't have access to our functions/aliases above, we have to duplicate their commands here. So those and these should remain in sync
-  # Using `npx` right now to reduce noise of saying `yarn run v1.x.x` right now, but could switch to yarn. Or could use bin below (but at that point, have to be in the project root for this to work. Or write some intelligent function that traverses upwards to find the project root, then use the `/node_modules/.bin` from there)
-  # local bin="$(pwd)/node_modules/.bin"
-  concurrently \
-    -n typescript,eslint,prettier -c "#4077ba,#7b7ee3,#efbd52" \
-    "npx tsc --noEmit" \
-    "npx eslint --max-warnings=0  --fix ." \
-    "npx prettier -write --loglevel=error ."
+#   # NOTE: Since concurrently doesn't have access to our functions/aliases above, we have to duplicate their commands here. So those and these should remain in sync
+#   # Using `npx` right now to reduce noise of saying `yarn run v1.x.x` right now, but could switch to yarn. Or could use bin below (but at that point, have to be in the project root for this to work. Or write some intelligent function that traverses upwards to find the project root, then use the `/node_modules/.bin` from there)
+#   # local bin="$(pwd)/node_modules/.bin"
+#   concurrently \
+#     -n typescript,eslint,prettier -c "#4077ba,#7b7ee3,#efbd52" \
+#     "npx tsc --noEmit" \
+#     "npx eslint --max-warnings=0  --fix ." \
+#     "npx prettier -write --loglevel=error ."
 
-  if git_has_changes; then
-    if [[ index_dirty -eq 0 ]]; then
-      gcim "cleanup"
-    fi
-  fi
-); }
-# "validate all" (static plus Jest tests)
-v() { (
-  # Exit and fail the function if any command in it fails. In a function, you have to add the parens to create a "subshell" in order for this to work. Without them, zsh itself crashes
-  # https://stackoverflow.com/questions/40429865/how-to-exit-bash-function-if-error
-  set -e
+#   if git_has_changes; then
+#     if [[ index_dirty -eq 0 ]]; then
+#       gcim "cleanup"
+#     fi
+#   fi
+# ); }
+# # "validate all" (static plus Jest tests)
+# v() { (
+#   # Exit and fail the function if any command in it fails. In a function, you have to add the parens to create a "subshell" in order for this to work. Without them, zsh itself crashes
+#   # https://stackoverflow.com/questions/40429865/how-to-exit-bash-function-if-error
+#   set -e
 
-  local index_dirty=0
-  if git_has_changes; then
-    echo "Uncommitted changes found; will not commit cleanup changes."
-    index_dirty=1
-  fi
+#   local index_dirty=0
+#   if git_has_changes; then
+#     echo "Uncommitted changes found; will not commit cleanup changes."
+#     index_dirty=1
+#   fi
 
-  if is_yarn_project; then
-    yarn
-  else
-    npm i
-  fi
+#   if is_yarn_project; then
+#     yarn
+#   else
+#     npm i
+#   fi
 
-  # NOTE: Since concurrently doesn't have access to our functions/aliases above, we have to duplicate their commands here. So those and these should remain in sync
-  # Using `npx` right now to reduce noise of saying `yarn run v1.x.x` right now, but could switch to yarn. Or could use bin below (but at that point, have to be in the project root for this to work. Or write some intelligent function that traverses upwards to find the project root, then use the `/node_modules/.bin` from there)
-  # local bin="$(pwd)/node_modules/.bin"
-  # Normally do this with `maxWorkers=50%`, but since we're doing this other stuff in parallel too, we have even less resources to work with, so 50% ends up being too much again
-  concurrently \
-    -n typescript,jest,eslint,prettier -c "#4077ba,#8f455b,#7b7ee3,#efbd52" \
-    "npx tsc --noEmit" \
-    "npx jest --changedSince=$(git_dev_branch) --coverage=false --maxWorkers=25%" \
-    "npx eslint --max-warnings=0 --fix ." \
-    "npx prettier -write --loglevel=error ."
+#   # NOTE: Since concurrently doesn't have access to our functions/aliases above, we have to duplicate their commands here. So those and these should remain in sync
+#   # Using `npx` right now to reduce noise of saying `yarn run v1.x.x` right now, but could switch to yarn. Or could use bin below (but at that point, have to be in the project root for this to work. Or write some intelligent function that traverses upwards to find the project root, then use the `/node_modules/.bin` from there)
+#   # local bin="$(pwd)/node_modules/.bin"
+#   # Normally do this with `maxWorkers=50%`, but since we're doing this other stuff in parallel too, we have even less resources to work with, so 50% ends up being too much again
+#   concurrently \
+#     -n typescript,jest,eslint,prettier -c "#4077ba,#8f455b,#7b7ee3,#efbd52" \
+#     "npx tsc --noEmit" \
+#     "npx jest --changedSince=$(git_dev_branch) --coverage=false --maxWorkers=25%" \
+#     "npx eslint --max-warnings=0 --fix ." \
+#     "npx prettier -write --loglevel=error ."
 
-  if git_has_changes; then
-    if [[ index_dirty -eq 0 ]]; then
-      gcim "cleanup"
-    fi
-  fi
-); }
+#   if git_has_changes; then
+#     if [[ index_dirty -eq 0 ]]; then
+#       gcim "cleanup"
+#     fi
+#   fi
+# ); }
 
 #####################################################################
 # Bat and Delta
